version: "3.7"

services:
  env_file:
    - ../global.env
    - .env
  ## Heimdall: a way to organise all those links to your most used web sites and web applications in a simple way. Simplicity is the key to Heimdall. ##
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/heimdall-data:/config
    networks:
      - default
      - traefik-network
    deploy:
      labels:
        ## Watchtower configuration ##
        - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}

        ## Diun configuration ##
        - diun.enable=${DIUN_ENABLE}

        ## Traefik configuration ##
        # Enable Traefik #
        - traefik.enable=true
        - traefik.docker.network=traefik-network

        # Set entrypoint port #
        - traefik.http.services.heimdall.loadbalancer.server.port=80

        # Set HTTP domain and HTTP -> HTTPS redirection #
        - traefik.http.routers.heimdall.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.heimdall.entrypoints=web
        - traefik.http.routers.heimdall.middlewares=https-redirect@file

        # Set HTTPS domain #
        - traefik.http.routers.heimdall-secure.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.heimdall-secure.entrypoints=websecure

networks:
  default:
    name: heimdall-network
  traefik-network:
    name: traefik-network
    external: true
